// Autogenerated Source File for React
import React from "react";

import ReactDOM from "react-dom";
import "./index.css"; // Import the CSS file
import App from "./App";

// reactdom.render() is the method that renders the react app to the DOM
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
